version: "3.7"

services:
  server:
    container_name: server
    build:
      context: "./backend"
      dockerfile: "./Dockerfile.graph"
    image: "area/server"
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    networks:
      - webnet
    volumes:
      - ${PWD}/backend:/app_graphql
  auth:
    build:
      context: "./backend"
      dockerfile: "./Dockerfile.auth"
    env_file:
      - ./backend/.env
    image: "area/auth"
    ports:
      - "5001:5001"
    networks:
      - webnet
    depends_on:
      - server
    volumes:
      - ${PWD}/backend:/app_auth
  client:
    build:
      context: "./client"
      dockerfile: "./Dockerfile"
    image: "area/client"
    env_file:
      - ./client/.env
    volumes:
      - ${PWD}/client:/app
    ports:
      - "8081:8081"

networks:
  webnet:
